spring:
  datasource:
     url: jdbc:sqlserver://virtualmachineserverdb1.database.windows.net:1433;database=VirtualmachineDB1;user=aviral@virtualmachineserverdb1;password=Avir@lbajpei10;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9191
